var art_styles = [
    "Surrealism",
    "Realism",
    "Abstract",
    "Impressionism",
    "Expressionism",
    "Gothic",
    "Renaissance",
    "Art Deco",
    "Rock Art",
    "Abstract Expressionism",
    "Art Nouveau",
    "Avant-garde",
    "Baroque",
    "Bauhaus",
    "Classicism",
    "Conceptual Art",
    "Constructivism",
    "Cubism",
    "Dadaism",
    "Fauvism",
    "Futurism",
    "Harlem Renaissance",
    "Installation Art",
    "Land Art",
    "Minimalism",
    "Neo-Impressionism",
    "Neoclassicism",
    "Neon Art",
    "Op Art",
    "Performance Art",
    "Pop Art",
    "Post-Impressionism",
    "Precisionism",
    "Rococo",
    "Suprematism",
    "Symbolism",
    "Zero Group",
    "Manga",
    "Anime",
    "Retro Graphics",
    "Retro 3D",
    "High-quality 3D",
    "Sketch",
    "Retro 2D",
    "Vector",
    "Black and white",
    "Colorful",
    "Bizarre",
    "Distorted",
    "Glitch Art",
    "Photomanipulation",
    "Propaganda",
    "Digital Art",
    "Assemblage",
    "Montage",
    "18th century",
    "19th century",
    "1920s",
    "1930s",
    "1940s",
    "1950s",
    "1960s",
    "1970s",
    "1980s",
    "1990s",
    "2000s",
    "2010s",
    "Synthwave",
    "Fresh",
    "Comic-book style",
    "Depressive",
    "Psychedelic",
    "Optical Illusion",
    "Mindbending",
    "Tribal",
    "Sci-fi",
    "Fantasy",
    "Gothic",
    "Germany",
    "Spain",
    "Portugal",
    "America",
    "China",
    "Russia",
    "Australia",
    "United Kingdom",
    "France",
    "Mexico",
    "Cuba",
    "Brazil",
    "Argentina",
    "African",
    "Japan",
    "Morocco",
    "India",
    "Pakistan",
    "Canada",
    "Eskimo",
    "Arab",
    "Robot",
    "Christian",
    "Buddhist",
    "Islam",
    "Zen",
    "Jewish",
    "Hindu",
    "Album art",
    "Game concept",
    "Visual Novel",
    "Award-winning",
    "4k",
    "Pixel Art",
    "Cartoon",
    "Cute",
    "Pixar",
    "Dreamworks",
    "Visual Effects",
    "VFX",
    "Fine Art",
    "Dark",
    "Darkness",
    "Bright",
    "Music Video",
    "Engraving",
    "Graphic Design",
    "Illustration",
    "Paper Arts",
    "DIY",
    "80s TV",
    "90s TV",
    "2000s TV",
    "Hollywood",
    "Bollywood",
    "Cinema",
    "Meaningful",
    "Mosaic",
    "Clean",
    "Messy",
    "Close-up",
    "Macro",
    "Landscape",
    "Portrait",
    "Commercial",
    "Advertising",
    "Premium",
    "Scrappy",
    "Vampires",
    "Zombies",
    "Disease",
    "realistic photo",
    "ultra-detailed",
    "ray tracing",
    "unreal engine"
];