var initial_prompts = [
    "Tell me a random animal",
    "Tell me a random tourist atraction",
    "Tell me a random food",
    "Tell me a random place",
    "Tell me a random object",
    "Tell me a random building",
    "Tell me a random natural wonder",
    "Tell me a random vehicle and specify the brand and model",
    "Tell me a random product and specify the brand and model",
    "Describe a city in the future in two sentences",
    "Describe a city in the 18th century in two sentences",
    "Describe a person in the 18th century in two sentences",
    "Describe a person in the future in two sentences",
    "Describe a city in a fantasy world in two sentences",
    "Describe an abstract concept in two sentences",
    "Describe a creature in a fantasy world in two sentences",
    "Describe the interior design of a random room in two sentences",
    "Describe the interior of a coffeeshop in two sentences",
    "Describe the interior of a restaurant in two sentences",
    "Describe the interior of a factory in two sentences",
    "Give me an idea for a meme",
    "Describe an event in two sentences",
    "Describe a funny situation in two sentences",
    "Describe a feeling in two sentences",
    "Describe a paranormal creature in two sentences",
    "Describe a random planet in two sentences",
    "Describe a random planet in two sentences as viewed from space",
    "Describe a weather condition in two sentences",
    "Tell me a random toy and specify the brand and model",
    "Describe a fictional movie poster in two sentences. You can use the following genres: action, adventure, comedy, crime, drama, fantasy, horror, mystery, romance, sci-fi, thriller, western",
    "Describe a fictional book cover in two sentences. You can use the following genres: action, adventure, comedy, crime, drama, fantasy, horror, mystery, romance, sci-fi, thriller, western",
    "Describe a realist painting in two sentences",
    "Describe a surreal painting in two sentences",
    "Describe a random painting in two sentences",
    "Describe a random sculpture in two sentences",
    "Describe a random piece of architecture in two sentences",
    "Describe a random piece of furniture in two sentences",
    "Describe a random piece of clothing in two sentences",
    "Describe a random motivational poster in two sentences",
    "Describe a person physically in two sentences",
    "Pretend you can do anything and describe a person's personality in two sentences",
    "Pretend tha tyou can do anything and write the description of a dream in two sentences",
    "Describe a random piece of jewelry in two sentences",
    "Describe a coreography in two sentences",
    "Describe a theatre scene in two sentences",
    "Describe a movie scene in two sentences",
    "Write a random slogan",
    "Write a random quote",
    "Write 3 random words",
    "Describe the world in two sentences",
    "Describe a problem in two sentences",
    "Pretend that you can do anything and describe society in 2 sentences"
];